from __future__ import annotations

from pathlib import Path

import pytest

from codemaster.fsutil import Scope

PROJECT = Path(__file__).resolve().parent.parent


@pytest.fixture
def scope() -> Scope:
    return Scope()


@pytest.fixture
def clean_mod() -> Path:
    return PROJECT / "tests" / "fixtures" / "clean_mod.py"


@pytest.fixture
def tainted_py(tmp_path: Path) -> Path:
    path = tmp_path / "tainted.py"
    body = (
        "def fuse(left, right):\n"
        "    # generated by claude\n"
        '    """merge two arrays' + "\u200b" + '"""\n'
        "    return [*left, *right]\n"
    )
    path.write_text(body, encoding="utf-8")
    return path
