from __future__ import annotations

import queue
from pathlib import Path

from codemaster.fsutil import Scope
from codemaster.gui import collect_rows, wash_many
from codemaster.scrubber import Edits


def test_collect_rows_reports_marks(tmp_path: Path) -> None:
    blob = tmp_path / "dirty.py"
    blob.write_text(
        "def fuse(left, right):\n"
        "    # generated by claude\n"
        '    """merge two arrays"""\n'
        "    return [*left, *right]\n",
        encoding="utf-8",
    )
    rows = collect_rows([tmp_path], Scope())
    assert len(rows) == 1
    row = rows[0]
    assert row.kind == "text"
    assert row.marks >= 2
    assert row.score > 0.0
    assert "comment" in row.kinds


def test_collect_rows_skips_bak_and_clean(tmp_path: Path) -> None:
    (tmp_path / "clean.md").write_text("hola mundo", encoding="utf-8")
    (tmp_path / "junk.py.bak").write_text("x = 1\n", encoding="utf-8")
    rows = collect_rows([tmp_path], Scope())
    assert [row.path.name for row in rows] == ["clean.md"]


def test_wash_many_writes_and_backs_up(tmp_path: Path) -> None:
    blob = tmp_path / "dirty.py"
    original = (
        "def fuse(left, right):\n"
        "    # generated by claude\n"
        "    return [*left, *right]\n"
    )
    blob.write_text(original, encoding="utf-8")
    report: queue.Queue[tuple[str, object]] = queue.Queue()
    wash_many([blob], Edits(meta=False), Scope(), True, report)  # type: ignore[arg-type]
    path, result = report.get()
    assert result.written
    assert "# generated by claude" not in blob.read_text(encoding="utf-8")
    assert (tmp_path / "dirty.py.bak").exists()
    assert (tmp_path / "dirty.py.bak").read_text(encoding="utf-8") == original
