from __future__ import annotations

from codemaster.report import Grade
from codemaster.signatures import match


def test_authorship_claim_is_danger() -> None:
    slips = match("result = 0  # generated by claude goes here")
    assert any(
        slip.kind == "authorship" and slip.rank is Grade.DANGER for slip in slips
    )


def test_model_mention_is_signal() -> None:
    slips = match("docs mention gemini in passing")
    assert any(slip.kind == "model" and slip.rank is Grade.SIGNAL for slip in slips)


def test_narration_filler_flagged() -> None:
    slips = match("keep in mind this pipeline is slow")
    assert any(slip.kind == "narration" for slip in slips)


def test_false_completeness_flagged() -> None:
    slips = match("// rest of the code follows")
    assert any(slip.kind == "fragment" for slip in slips)


def test_clean_text_silent() -> None:
    assert match("def compute(flag):\n    return 2 if flag else 5\n") == []


def test_container_matches_deduplicated() -> None:
    slips = match("as an ai language model I answer")
    assert sum(1 for slip in slips if slip.kind == "authorship") == 1
