from __future__ import annotations

from pathlib import Path

from codemaster.scrubber import Edits, scrub_text, wash_file


def test_scrub_text_removes_docstrings_and_comments() -> None:
    source = (
        "def fuse(left, right):\n"
        "    # generated by claude\n"
        '    """merge two arrays"""\n'
        "    return [*left, *right]\n"
    )
    cleaned, labels = scrub_text(source, True, Edits())
    assert "#" not in cleaned
    assert "merge two arrays" not in cleaned
    assert "def fuse(" in cleaned
    assert "return [*left, *right]" in cleaned
    assert "docstrings" in labels
    assert "comments" in labels


def test_scrub_text_keeps_non_python_unchanged() -> None:
    body = "# heading\nbody text\n"
    cleaned, labels = scrub_text(body, False, Edits())
    assert cleaned == body
    assert labels == []


def test_glyph_flush_via_edits() -> None:
    source = "mark" + "\u200b" + "er\n"
    cleaned, labels = scrub_text(source, False, Edits(glyphs=True))
    assert cleaned == "marker\n"
    assert "glyphs" in labels


def test_dry_run_does_not_touch_disk(tmp_path: Path) -> None:
    path = tmp_path / "dirty.py"
    body = "def f():\n    # note that x is huge\n    return x\n"
    path.write_text(body, encoding="utf-8")
    result = wash_file(path, Edits(), apply_write=False)
    assert result.altered
    assert not result.written
    assert path.read_text(encoding="utf-8") == body


def test_apply_with_backup(tmp_path: Path) -> None:
    path = tmp_path / "dirty.py"
    body = "def g():\n    # generated by chatgpt\n    return 0\n"
    path.write_text(body, encoding="utf-8")
    result = wash_file(path, Edits(), backup=True, apply_write=True)
    assert result.written
    assert result.backup is not None
    assert result.backup.exists()
    assert result.backup.read_text(encoding="utf-8") == body
    rewritten = path.read_text(encoding="utf-8")
    assert "#" not in rewritten
    assert "return 0" in rewritten


def test_apply_when_already_clean(tmp_path: Path) -> None:
    path = tmp_path / "pure.py"
    body = "def h():\n    return 1\n"
    path.write_text(body, encoding="utf-8")
    result = wash_file(path, Edits(), apply_write=True)
    assert not result.altered
    assert not result.written
    assert path.read_text(encoding="utf-8") == body


def test_scrub_overlapping_docstring_and_comment() -> None:
    source = (
        "def fuse(a, b):\n"
        "    # a comment inside the function\n"
        '    """a docstring following a comment"""\n'
        "    return a + b\n"
    )
    cleaned, labels = scrub_text(source, True, Edits())
    assert "comment" not in cleaned
    assert "docstring" not in cleaned
    assert "def fuse(" in cleaned
    assert "return a + b" in cleaned
    assert set(labels) == {"comments", "docstrings"}


def test_module_docstring_and_multiline() -> None:
    source = (
        '"""Module level summary.\n'
        "More details here.\n"
        '"""\n'
        "async def run():\n"
        '    """async docstring covering one line"""\n'
        "    return 1\n"
    )
    cleaned, labels = scrub_text(source, True, Edits())
    assert "Module level summary" not in cleaned
    assert "async docstring" not in cleaned
    assert "async def run():" in cleaned
    assert "docstrings" in labels


def test_keep_docstrings_off() -> None:
    source = 'def f():\n    """kept docs"""\n    # removed comment\n    return 1\n'
    cleaned, labels = scrub_text(source, True, Edits(docstrings=False))
    assert '"kept docs"' in cleaned
    assert "removed comment" not in cleaned
    assert "comments" in labels
    assert "docstrings" not in labels


def test_span_merging_adjacent() -> None:
    source = "def f():\n    # first\n    # second\n    return 1\n"
    cleaned, _ = scrub_text(source, True, Edits())
    assert "#" not in cleaned


def test_latin1_codec_roundtrip(tmp_path: Path) -> None:
    path = tmp_path / "iso.py"
    body = "# caf\xe9 note\nx = 1\n"
    path.write_bytes(body.encode("latin-1"))
    result = wash_file(path, Edits(), apply_write=True)
    assert result.altered
    assert "caf\xe9" not in path.read_bytes().decode("latin-1")
    assert "x = 1" in path.read_bytes().decode("latin-1")
