from __future__ import annotations

from pathlib import Path

from codemaster import portal
from codemaster.fsutil import Scope
from codemaster.report import render_html, render_json, render_markdown


def _seed(tmp_path: Path) -> None:
    (tmp_path / "a.py").write_text(
        "def f():\n    # generated by claude\n    return 1\n", encoding="utf-8"
    )
    (tmp_path / "b.md").write_text("Note that this is nice.\n", encoding="utf-8")
    (tmp_path / "clean.md").write_text("hola\n", encoding="utf-8")


def test_tour_parallel_progress(tmp_path: Path) -> None:
    _seed(tmp_path)
    seen: list[tuple[int, int]] = []

    def progress(done: int, total: int) -> None:
        seen.append((done, total))

    ledger = portal.tour_parallel([tmp_path], Scope(), workers=3, progress=progress)
    assert len(ledger.sheets) == 3
    assert seen
    assert seen[-1][0] == seen[-1][1]
    assert ledger.worst().name == "DANGER"


def test_tour_parallel_empty_reports_progress(tmp_path: Path) -> None:
    events: list[tuple[int, int]] = []

    def progress(done: int, total: int) -> None:
        events.append((done, total))

    ledger = portal.tour_parallel([tmp_path], Scope(), progress=progress)
    assert ledger.sheets == []
    assert events == [(0, 0)]


def test_tour_parallel_cancel(tmp_path: Path) -> None:
    _seed(tmp_path)
    ledger = portal.tour_parallel([tmp_path], Scope(), workers=2, cancel=lambda: True)
    assert ledger.sheets == []


def test_wash_atomic_writes_and_backup(tmp_path: Path) -> None:
    from codemaster.scrubber import Edits

    blob = tmp_path / "a.py"
    original = "def f():\n    # generated by claude\n    return 1\n"
    blob.write_text(original, encoding="utf-8")
    result = portal.wash_path(
        blob, Edits(meta=False), Scope(), backup=True, apply_write=True
    )
    assert result.written
    assert (tmp_path / "a.py.bak").read_text(encoding="utf-8") == original
    assert "# generated" not in blob.read_text(encoding="utf-8")
    assert not any(tmp_path.glob("*.cmtmp"))


def test_wash_atomic_rolls_back_on_rename_failure(tmp_path: Path, monkeypatch) -> None:
    import os

    import pytest

    from codemaster.scrubber import Edits

    blob = tmp_path / "a.py"
    original = "def f():\n    # generated by claude\n    return 1\n"
    blob.write_text(original, encoding="utf-8")

    def boom(_src: str, _dst: str) -> None:
        raise OSError("boom")

    monkeypatch.setattr(os, "replace", boom)
    with pytest.raises(OSError):
        portal.wash_path(
            blob, Edits(meta=False), Scope(), backup=True, apply_write=True
        )
    assert blob.read_text(encoding="utf-8") == original
    assert not any(tmp_path.glob("*.cmtmp"))


def test_report_markdown_includes_verdict(tmp_path: Path) -> None:
    _seed(tmp_path)
    ledger = portal.tour([tmp_path], Scope())
    md = render_markdown(ledger)
    assert md.startswith("# Reporte de huellas AI")
    assert "DANGER" in md
    assert "authorship" in md
    assert "clean.md" not in md


def test_report_html_escapes(tmp_path: Path) -> None:
    _seed(tmp_path)
    ledger = portal.tour([tmp_path], Scope())
    html = render_html(ledger)
    assert "<table>" in html
    assert 'class="danger"' in html


def test_report_json_structure(tmp_path: Path) -> None:
    import json

    _seed(tmp_path)
    ledger = portal.tour([tmp_path], Scope())
    payload = json.loads(render_json(ledger))
    assert payload["worst"] == "danger"
    assert "totals" in payload
    assert len(payload["files"]) == 3


def test_group_totals_counts_model_groups(tmp_path: Path) -> None:
    blob = tmp_path / "mix.md"
    blob.write_text(
        "video with sora and voice via elevenlabs, drafted by claude\n",
        encoding="utf-8",
    )
    ledger = portal.tour([tmp_path], Scope())
    groups = ledger.group_totals()
    assert groups.get("video") == 1
    assert groups.get("audio") == 1
    assert groups.get("llm") == 1
    sheet = ledger.sheets[0]
    model_marks = [m for m in sheet.marks if m.kind == "model"]
    assert all(m.group for m in model_marks)


def test_report_markdown_shows_groups(tmp_path: Path) -> None:
    blob = tmp_path / "mix.md"
    blob.write_text("video with sora\n", encoding="utf-8")
    ledger = portal.tour([tmp_path], Scope())
    md = render_markdown(ledger)
    assert "Grupos:" in md
    assert "[video]" in md


def test_filter_groups_keeps_only_selected(tmp_path: Path) -> None:
    blob = tmp_path / "mix.md"
    blob.write_text(
        "video with sora and voice via elevenlabs, drafted by claude\n",
        encoding="utf-8",
    )
    ledger = portal.tour([tmp_path], Scope())
    video_only = ledger.filter_groups(frozenset({"video"}))
    assert video_only.sheets[0].marks
    assert all(m.group == "video" for m in video_only.sheets[0].marks)
    empty = ledger.filter_groups(frozenset({"code"}))
    assert empty.sheets == []


def test_evidence_strength(tmp_path: Path) -> None:
    weak = tmp_path / "weak.md"
    weak.write_text("mentions claude\n", encoding="utf-8")
    strong = tmp_path / "strong.py"
    strong.write_text(
        "def f():\n    # generated by claude\n    return 1\n", encoding="utf-8"
    )
    ledger = portal.tour([tmp_path], Scope())
    sheets = {sheet.path.name: sheet for sheet in ledger.sheets}
    assert sheets["weak.md"].evidence() == "weak"
    assert sheets["strong.py"].evidence() == "strong"


def test_filter_kinds_keeps_only_selected(tmp_path: Path) -> None:
    blob = tmp_path / "mix.py"
    blob.write_text(
        "def f():\n    # generated by claude\n    return 1\n", encoding="utf-8"
    )
    ledger = portal.tour([tmp_path], Scope())
    models_only = ledger.filter_kinds(frozenset({"model"}))
    if models_only.sheets:
        assert all(m.kind == "model" for m in models_only.sheets[0].marks)
