from __future__ import annotations

import json
from pathlib import Path

from codemaster.cli import main


def test_scan_json_reports_dirty(capsys, tainted_py) -> None:
    code = main(["scan", "--json", str(tainted_py)])
    assert code == 0
    payload = json.loads(capsys.readouterr().out)
    assert payload["worst"] == "danger"
    kinds = payload["files"][0]["marks"]
    labels = {mark["kind"] for mark in kinds}
    assert {"comment", "docstring", "stealth", "authorship"} <= labels


def test_scan_json_scores_dirty_positive(capsys, tainted_py) -> None:
    main(["scan", "--json", str(tainted_py)])
    sheet = json.loads(capsys.readouterr().out)["files"][0]
    assert sheet["score"] > 0.0
    assert sheet["score"] <= 1.0


def test_scan_json_scores_clean_zero(capsys, clean_mod) -> None:
    main(["scan", "--json", str(clean_mod)])
    sheet = json.loads(capsys.readouterr().out)["files"][0]
    assert sheet["score"] == 0.0


def test_scan_human_mentions_totals(capsys, tainted_py) -> None:
    main(["scan", str(tainted_py)])
    output = capsys.readouterr().out
    assert "verdict: DANGER" in output
    assert "totals:" in output


def test_check_fails_on_dirty(tainted_py) -> None:
    assert main(["check", str(tainted_py)]) == 1


def test_check_passes_on_clean(clean_mod) -> None:
    assert main(["check", str(clean_mod)]) == 0


def test_check_strict_fails_on_signal(capsys, tmp_path: Path) -> None:
    path = tmp_path / "stray.md"
    path.write_text("keep in mind this file is plain\n", encoding="utf-8")
    assert main(["check", "--strict", str(path)]) == 1
    assert main(["check", str(path)]) == 0


def test_scrub_apply_rewrites(capsys, tmp_path: Path) -> None:
    path = tmp_path / "messy.py"
    body = "def walk(trail):\n    # generated by claude\n    return trail\n"
    path.write_text(body, encoding="utf-8")
    code = main(["scrub", "--apply", "--backup", str(path)])
    assert code == 0
    assert "rewritten" in capsys.readouterr().out
    assert "#" not in path.read_text(encoding="utf-8")
    assert (tmp_path / "messy.py.bak").exists()


def test_scrub_dry_run_writes_nothing(capsys, tmp_path: Path) -> None:
    path = tmp_path / "messy.py"
    path.write_text(
        "def walk(trail):\n    # generated by claude\n    return trail\n",
        encoding="utf-8",
    )
    main(["scrub", str(path)])
    assert "would rewrite" in capsys.readouterr().out
    assert "# generated by claude" in path.read_text(encoding="utf-8")


def test_scope_exclude_skips_directories(capsys, tmp_path: Path) -> None:
    nested = tmp_path / "vendor"
    nested.mkdir()
    dirty = nested / "vendor_mod.py"
    dirty.write_text(
        "def f():\n    # generated by claude\n    return 1\n", encoding="utf-8"
    )
    clean = tmp_path / "mine.py"
    clean.write_text("def f():\n    return 1\n", encoding="utf-8")
    assert main(["check", str(tmp_path)]) == 1
    assert main(["check", str(tmp_path), "--exclude", "vendor"]) == 0
