from __future__ import annotations

import json
import socket
import threading
from pathlib import Path
from urllib.request import urlopen

from codemaster.web import serve


def _free_port() -> int:
    with socket.socket() as sock:
        sock.bind(("127.0.0.1", 0))
        return int(sock.getsockname()[1])


def _server():
    port = _free_port()
    server = serve("127.0.0.1", port)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    return server, port, thread


def _url(port: int, path: str) -> str:
    return f"http://127.0.0.1:{port}{path}"


def _stop(server, thread) -> None:
    server.shutdown()
    server.server_close()
    thread.join(timeout=2)


def test_index_served(tmp_path: Path) -> None:
    server, port, thread = _server()
    try:
        with urlopen(_url(port, "/"), timeout=10) as resp:
            body = resp.read().decode("utf-8")
            assert resp.status == 200
            assert "CodeMaster" in body
            assert "three" in body
            assert resp.headers.get("Cache-Control") == "no-store"
    finally:
        _stop(server, thread)


def test_api_config(tmp_path: Path) -> None:
    server, port, thread = _server()
    try:
        with urlopen(_url(port, "/api/config"), timeout=10) as resp:
            payload = json.loads(resp.read().decode())
            assert "workers" in payload
            assert "backup" in payload
    finally:
        _stop(server, thread)


def test_api_history_empty(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.setenv("CODEMASTER_HOME", str(tmp_path / ".cm"))
    server, port, thread = _server()
    try:
        with urlopen(_url(port, "/api/history"), timeout=10) as resp:
            payload = json.loads(resp.read().decode())
            assert payload["entries"] == []
    finally:
        _stop(server, thread)


def test_api_scan_sse(tmp_path: Path) -> None:
    (tmp_path / "a.py").write_text(
        "def f():\n    # generated by claude\n    return 1\n", encoding="utf-8"
    )
    server, port, thread = _server()
    try:
        with urlopen(
            _url(port, f"/api/scan?path={tmp_path}&stream=0"), timeout=20
        ) as resp:
            payload = json.loads(resp.read().decode())
        assert payload["type"] == "done"
        assert len(payload["files"]) == 1
        assert payload["worst"] == "danger"
    finally:
        _stop(server, thread)


def test_api_clean(tmp_path: Path, monkeypatch) -> None:
    from urllib.request import Request

    monkeypatch.setenv("CODEMASTER_HOME", str(tmp_path / ".cm"))
    blob = tmp_path / "a.py"
    blob.write_text(
        "def f():\n    # generated by claude\n    return 1\n", encoding="utf-8"
    )
    server, port, thread = _server()
    try:
        data = json.dumps(
            {"paths": [str(blob)], "backup": True, "comments": True}
        ).encode()
        req = Request(
            _url(port, "/api/clean"),
            data=data,
            headers={"Content-Type": "application/json"},
        )
        with urlopen(req, timeout=20) as resp:
            payload = json.loads(resp.read().decode())
        assert payload["washed"] == 1
        assert (tmp_path / "a.py.bak").exists()
        assert "# generated" not in blob.read_text(encoding="utf-8")
        assert (tmp_path / ".cm" / "history.jsonl").exists()
    finally:
        _stop(server, thread)


def test_api_report_markdown(tmp_path: Path) -> None:
    (tmp_path / "a.py").write_text(
        "def f():\n    # generated by claude\n    return 1\n", encoding="utf-8"
    )
    server, port, thread = _server()
    try:
        with urlopen(
            _url(port, f"/api/report?path={tmp_path}&format=md"), timeout=10
        ) as resp:
            body = resp.read().decode()
            assert body.startswith("# Reporte de huellas AI")
    finally:
        _stop(server, thread)


def test_api_list_dirs(tmp_path: Path) -> None:
    (tmp_path / "sub").mkdir()
    (tmp_path / "plain.txt").write_text("x", encoding="utf-8")
    server, port, thread = _server()
    try:
        with urlopen(_url(port, f"/api/list?path={tmp_path}"), timeout=10) as resp:
            payload = json.loads(resp.read().decode())
        assert payload["path"] == str(tmp_path)
        assert [d["name"] for d in payload["dirs"]] == ["sub"]
        assert payload["parent"] is not None
    finally:
        _stop(server, thread)


def test_api_list_falls_back_on_missing(tmp_path: Path) -> None:
    server, port, thread = _server()
    try:
        with urlopen(
            _url(port, "/api/list?path=" + str(tmp_path / "nope")), timeout=10
        ) as resp:
            payload = json.loads(resp.read().decode())
        assert payload["path"]
    finally:
        _stop(server, thread)
