from __future__ import annotations

import struct
from pathlib import Path

HERE = Path(__file__).resolve().parent
DEMO = HERE / "ai-traces"

DEMO.mkdir(exist_ok=True)


def write_py() -> None:
    (DEMO / "app.py").write_text(
        "def build_report(data):\n"
        "    # generated by claude\n"
        '    """Aggregate rows into a summary table.\u200b"""\n'
        "    return [row for row in data]\n",
        encoding="utf-8",
    )


def write_md() -> None:
    (DEMO / "notas.md").write_text(
        "# Notas\n"
        "\n"
        "Note that this feature also supports batches. Feel free to extend it.\n"
        "\n"
        "Keep in mind that `chatgpt` can summarize this.\n",
        encoding="utf-8",
    )


def write_jpeg() -> None:
    body = (
        b"\xff\xd8\xff\xe0" + struct.pack(">H", 16) + b"JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00"
        + b"\xff\xe1" + struct.pack(">H", 22)
        + b"Exif\x00\x00"
        + b"II*\x00\x08\x00\x00\x00\x01\x00"
        + b"\x00\x00\x90\x01\x03\x00\x01\x00\x00\x00"
        + b"\xff\xd9"
    )
    (DEMO / "foto.jpg").write_bytes(body)


def write_gif() -> None:
    try:
        from PIL import Image
    except ImportError:
        (DEMO / "anim.gif").write_bytes(
            b"GIF89a" + b"\x00\x00\x00\x00" + b"!\xfe" + b"\x0b" + b"AI Generated" + b"\x00;"
        )
        return
    image = Image.new("RGB", (8, 8), "blue")
    image.save(DEMO / "anim.gif", comment=b"AI Generated")


write_py()
write_md()
write_jpeg()
write_gif()
print("ok")